import type { Metadata } from "next";
import SmoothScrollProvider from "../Providers/SmoothScrollProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/common/Navbar";
import Footer from "@/Components/common/Footer";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const giaconda = localFont({
  src: [
    {
      path: "../public/fonts/guiconda/Giuconda-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/guiconda/Giuconda-Semi-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/guiconda/Giuconda-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-giuconda",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${giaconda.variable} antialiased`}
      >
        <SmoothScrollProvider>
          <Navbar />
          {children}
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
